#!/usr/bin/env bash
# Install nignix on your server
sudo apt-get update -y
sudo apt-get install nginx -y

sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
