#!/usr/bin/env bash
# Install nignix on your server

sudo apt-get update -y
sudo apt-get install nginx -y

sudo service nginx start


echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/' /etc/nginx/sites-available/default

sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
