#!/usr/bin/env bash

sudo apt-get update -y
sudo apt-get install nginx -y

sudo service nginx start


echo "Hello World!" | sudo tee /var/www/html/index.html >/dev/null

sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
