#!/usr/bin/env bash
# This script installs nginx on ubuntu server

sudo apt-get install -y nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'


echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

line="https://www.youtube.com"

sudo sed -i "/ubuntu;/ redirect_me {\n    return 301 $line;\n    }"

sudo nginx -s reload
