#!/usr/bin/env bash
# Update package list and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

hostname=$(hostname)

sudo sed -i "/server_name _;/a \    add_header X-Served-By $hostname;" /etc/nginx/sites-available/default

sudo nginx -s reload
