#! /usr/bin/env bash
#install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo chown $USER:USER /etc/haproxy/haproxy.cfg

server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 379819-web-01 34.224.1.240:80 check
        server 379819-web-02 35.168.2.175:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
